// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW3qPSrofsoiKQsfDMRN_SmV14q-G0xZc',
    appId: '1:81071616396:web:c052485f22abe8f56266a9',
    messagingSenderId: '81071616396',
    projectId: 'nursery-plant-app-51e1e',
    authDomain: 'nursery-plant-app-51e1e.firebaseapp.com',
    storageBucket: 'nursery-plant-app-51e1e.firebasestorage.app',
    measurementId: 'G-B3BNWJ67YX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcgPfC1DNDVR0ilXeEOpmUnPPcKGe7cE',
    appId: '1:81071616396:ios:ebacfbeb0a98d0c36266a9',
    messagingSenderId: '81071616396',
    projectId: 'nursery-plant-app-51e1e',
    storageBucket: 'nursery-plant-app-51e1e.firebasestorage.app',
    iosClientId: '81071616396-ek24ii99isqv6jtrtrurukoml3qgs870.apps.googleusercontent.com',
    iosBundleId: 'com.example.localPlantNurseriesApp',
  );

}